#!/bin/bash

# assumed to be run by administrator user
source /opt/ros/noetic/setup.bash
source /home/administrator/cartographer_ws/devel_isolated/setup.bash

mkdir ~/Desktop/cartographer_maps
cd ~/Desktop/cartographer_maps

# for XDISPLAY server for rviz
sudo xhost local:root &>/dev/null

rosnode kill /pose_integrator
# record ros topics for high-def map & offline slam parameter tuning
rosbag record /hsrb/base_imu/data /hsrb/base_scan /hsrb/odom /tf /tf_static &>/dev/null &
# kill any lingering, previous SLAM processes
sudo pkill cart
roslaunch cartographer_toyota_hsr carl_map.launch &
rosrun rviz rviz -d /home/administrator/Desktop/cartographer.rviz &

